### ISSUE TITLE
SocialController not redirecting

### ISSUE THREAD

**Issue by yanquisalexander** [renoki-co/hej#7]
Hello! 👋🏻 

Maybe it's a misconfiguration on my part, but Hej doesn't redirect to provider 😕 

I've been checking `RenokiCo\Hej\Http\Controllers\SocialController`, and apparently `@redirect` and `@callback` are not present, however I did find them in `Concerns\HandlesSocialRequests.php` 🤔 

Could it be a mistake?

**Comment by rennokki** [comment]
It's not a problem because it is used as a trait: https://github.com/renoki-co/hej/blob/master/src/Http/Controllers/SocialController.php#L15

Whitelist your provider names: https://github.com/renoki-co/hej#provider-whitelisting
